services:
  - type: web
    name: ashakids-spring
    runtime: docker
    rootDir: backend-spring
    plan: free

  - type: web
    name: ashakids-zoom
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    rootDir: backend-zoom
    plan: free

  - type: web
    name: ashakids-mail
    runtime: static
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT -t .
    rootDir: backend-mail
    plan: free
