services:
  - type: web
    name: ashakids-spring
    runtime: docker
    rootDir: backend-spring

  - type: web
    name: ashakids-zoom
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    rootDir: backend-zoom

  - type: web
    name: ashakids-mail
    runtime: docker
    rootDir: backend-mail
